#ifndef __LV_GUI_CONF_H_
#define __LV_GUI_CONF_H_

#define GUI_MARGIN 4
#define GUI_SCREEN_START_MARGIN 28

#define GUI_BUTTON_MENU_HEIGHT 24
#define GUI_BUTTON_MENU_WIDTH 140

#define GUI_TRIM_BAR_HEIGHT 16

#define GUI_CH_BAR_HEIGHT 12
#define GUI_CH_BAR_WIDTH 150
#define NUMBER_OF_CHANNELS 16
#define NUMBER_OF_CHANNELS 16
#define NUMBER_OF_HALF_PART_CHANNELS NUMBER_OF_CHANNELS / 2

#define GUI_SLIDER_CONTAINER_HEIGHT 24

#define GUI_ENDPOINT_MIN -100
#define GUI_ENDPOINT_MAX 100

#define GUI_BAR_MIN GUI_CH_MIN
#define GUI_BAR_MAX GUI_CH_MAX

#define GUI_TRIM_MIN -100
#define GUI_TRIM_MAX 100

#define GUI_DATA_UPDATE_PERIOD 500     // ms
#define GUI_DATA_UPDATE_PERIOD_FAST 20 // ms

#endif