/*
 * guiconfig.h
 *
 *  Created on: 27 ����. 2020 �.
 *      Author: ivnss
 */

#ifndef INC_STGUI_GUICONFIG_H_
#define INC_STGUI_GUICONFIG_H_


#define ENCODER_MENU_STEP_PER_ITEM		3
#define ENCODER_INPUT_STEP_PER_UNIT		1
#define ENCODER_PULSES_PER_STEP			4


#define CONTROL_METHOD					1				// 1 - Encoder
														// 2 - Keyboard

/***********************************
 *  GUI
 *
 *  RGB565 RRRRRGGGGGGBBBBB
 ***********************************/

#define GUI_MAX_WIDTH_PX					240
#define GUI_MAX_HEIGHT_PX					320
#define GUI_SCREEN_HEADER_HEIGHT_PX			20
/*
 * Main menu
 */
#define MAIN_MENU_WIDTH						180
#define MAIN_MENU_HEIGHT					280
#define MAIN_MENU_BACK_COLOR				0x7CF6
#define MAIN_MENU_HEADER_COLOR				0x42EE
#define MAIN_MENU_HEADER_TEXT_COLOR			0x7CF6
#define MAIN_MENU_BORDER_COLOR				0xC658
#define MAIN_MENU_BORDER_THICKNESS			2
#define MAIN_MENU_BUTTON_WIDTH				160
#define MAIN_MENU_BUTTON_HEIGHT				20
#define MAIN_MENU_BUTTON_X					(GUI_MAX_WIDTH_PX - MAIN_MENU_BUTTON_WIDTH)/2
#define MAIN_MENU_BUTTON_Y 					50
#define MAIN_MENU_BUTTON_STEP				MAIN_MENU_BUTTON_HEIGHT + 2
#define MAIN_BACK_BUTTON_X					1
#define MAIN_BACK_BUTTON_Y					293
#define MAIN_BACK_BUTTON_WIDTH				50
#define MAIN_BACK_BUTTON_HEIGHT				20
#define MAIN_HEADER_COLOR					0x7CF6
#define MAIN_HEADER_TEXT_COLOR				0x42CD
#define MAIN_HEADER_HEIGHT					18

/*
 * Ack screen
 */
#define ACK_SCREEN_WIDTH					164
#define ACK_SCREEN_HEIGHT					80
#define ACK_YES_BUTTON_X					50
#define ACK_NO_BUTTON_X						130
#define ACK_BUTTON_Y						154
#define ACK_BUTTON_WIDTH					60
#define ACK_BUTTON_HEIGHT					30

/*
 * Main screen
 */
#define MAIN_SCREEN_BACK_COLOR				0x42EE
#define MODELNAME_COLOR						0xD249
#define MODEL_NAME_X						1
#define MODEL_NAME_Y						20

/*
 * Progress Bar and Channel Bar
 */
#define BASE_BAR_BORDER_THICKNESS			2
#define BASE_BAR_GAP						2
#define BASE_BAR_BACK_COLOR					0x324B
#define BASE_BAR_BORDER_COLOR				0xC658
#define BASE_BAR_COLOR						0xC658
#define BASE_BAR_CENTER_COLOR				0xD249
#define BASE_BAR_CENTER_WIDTH				2
#define FOCUS_BAR_BORDER_THICKNESS			2
#define FOCUS_BAR_GAP						2
#define FOCUS_BAR_BACK_COLOR				0xC5B4
#define FOCUS_BAR_BORDER_COLOR				0x39E7
#define FOCUS_BAR_COLOR						0x39E7
#define FOCUS_BAR_CENTER_COLOR				0xC5B4

/*
 * Text Box
 */
#define TEXT_BUFF_SIZE						24
#define BASE_TEXT_COLOR						0xC658
#define BASE_TEXT_BORDER_THICKNESS			0
#define BASE_TEXT_BORDER_COLOR				0xC658
#define BASE_TEXT_BACK_COLOR				0x42EE
#define FOCUS_TEXT_COLOR					0xC658
#define FOCUS_TEXT_BORDER_THICKNESS			0
#define FOCUS_TEXT_BORDER_COLOR				0xC658
#define FOCUS_TEXT_BACK_COLOR				0x324B
#define BASE_TEXT_GAP						2

/*
 * Input Box
 */
#define INPUT_BUFF_SIZE						8
#define INPUT_BASE_HEIGHT					17
#define INPUT_BASE_WIDTH					50
#define BASE_INPUT_TEXT_COLOR				0x324B
#define BASE_INPUT_COLOR					0xC658
#define BASE_INPUT_BORDER_THICKNESS			2
#define BASE_INPUT_BORDER_COLOR				0x3186
#define BASE_INPUT_BACK_COLOR				0xBD94
#define FOCUS_INPUT_COLOR					0x21EA//0x3186
#define FOCUS_INPUT_BORDER_THICKNESS		2
#define FOCUS_INPUT_TEXT_COLOR				0xE655//0x42EE
#define FOCUS_INPUT_BORDER_COLOR			0xE655//0xFA48//0xBD94
#define FOCUS_INPUT_BACK_COLOR				0x21EA//0xC658
#define BASE_INPUT_GAP						2

/*
 * List Box
 */
#define LISTBOX_ITEMS						64
#define LISTBOX_BUFF_SIZE					16
#define LISTBOX_BASE_HEIGHT					26
#define LISTBOX_BASE_WIDTH					80
#define BASE_LISTBOX_TEXT_COLOR				0x324B
#define BASE_LISTBOX_COLOR					0xC658
#define BASE_LISTBOX_BORDER_THICKNESS		2
#define BASE_LISTBOX_BORDER_COLOR			0x3186
#define BASE_LISTBOX_BACK_COLOR				0xBD94
#define FOCUS_LISTBOX_COLOR					0x21EA//0x3186
#define FOCUS_LISTBOX_BORDER_THICKNESS		2
#define FOCUS_LISTBOX_TEXT_COLOR			0xE655//0x42EE
#define FOCUS_LISTBOX_BORDER_COLOR			0xE655//0xFA48//0xBD94
#define FOCUS_LISTBOX_BACK_COLOR			0x21EA//0xC658
#define BASE_LISTBOX_GAP					2
#define LISTBOX_BLINK_PERIOD				500

/*
 * Out fileld
 */
#define BASE_OUTPUT_TEXT_COLOR				0x3186
#define BASE_OUTPUT_COLOR					0x3186
#define BASE_OUTPUT_BORDER_THICKNESS		2
#define BASE_OUTPUT_BORDER_COLOR			0x3186
#define BASE_OUTPUT_BACK_COLOR				0xBD94
#define FOCUS_OUTPUT_COLOR					0x3186
#define FOCUS_OUTPUT_BORDER_THICKNESS		2
#define FOCUS_OUTPUT_TEXT_COLOR				0xC658
#define FOCUS_OUTPUT_BORDER_COLOR			0x3186
#define FOCUS_OUTPUT_BACK_COLOR				0xC658
#define BASE_OUTPUT_GAP						2

/*
 * Button
 */
#define BASE_BUTTON_COLOR					0xC658
#define BASE_BUTTON_BORDER_THICKNESS		2
#define BASE_BUTTON_BORDER_COLOR			0xC658
#define BASE_BUTTON_BACK_COLOR				0x3A4A
#define FOCUS_BUTTON_COLOR					0x3186
#define FOCUS_BUTTON_BORDER_THICKNESS		3
#define FOCUS_BUTTON_BORDER_COLOR			0x3186
#define FOCUS_BUTTON_BACK_COLOR				0xBD94

/*
 * CheckBox
 */
#define BASE_CHECKBOX_HEIGHT				16
#define BASE_CHECKBOX_WIDTH					36
#define BASE_CHECKBOX_ON_COLOR				0x43AC
#define BASE_CHECKBOX_OFF_COLOR				0xD180
#define BASE_CHECKBOX_TEXT_COLOR			0x1189
#define BASE_CHECKBOX_BORDER_THICKNESS		2
#define BASE_CHECKBOX_BORDER_COLOR			0x1189
#define FOCUS_CHECKBOX_BORDER_THICKNESS		2
#define FOCUS_CHECKBOX_BORDER_COLOR			0xBD94

/*
 * GraphPlot
 */
#define BASE_GRAPHPLOT_BORDER_THICKNESS		2
#define BASE_GRAPHPLOT_AXIS_THICKNESS		1
#define BASE_GRAPHPLOT_LINE_WIDTH			1
#define BASE_GRAPHPLOT_BACK_COLOR			0x324B
#define BASE_GRAPHPLOT_BORDER_COLOR			0xC658
#define BASE_GRAPHPLOT_COLOR				0xD249
#define BASE_GRAPHPLOT_CENTER_COLOR			0xD249
#define BASE_GRAPHPLOT_CENTER_WIDTH			2
#define FOCUS_GRAPHPLOT_BORDER_THICKNESS 	2
#define FOCUS_GRAPHPLOT_GAP					2
#define FOCUS_GRAPHPLOT_BACK_COLOR			0xBD94
#define FOCUS_GRAPHPLOT_BORDER_COLOR		0x3186
#define FOCUS_GRAPHPLOT_COLOR				0x3186
#define FOCUS_GRAPHPLOT_CENTER_COLOR		0x3186

/*
 * Screen Saver
 */
#define SCREEN_SAVER_BACK_COLOR				0x0000
#define SCREEN_SAVER_MAIN_COLOR				0xBD94


#endif /* INC_STGUI_GUICONFIG_H_ */
